/* eslint-disable */ /**
  *
  * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
  *
  * instead, edit one of the `.graphql` files in this project and run
  *
  * npm run graphql-codegen
  *
  * for this file to be re-created
  */

import * as Types from '../../generated/types.generated';

import { graphqlApiSlice } from 'api/graphql-api-slice.ts';
module.hot?.accept();
export type GetCountriesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetCountriesQuery = { __typename?: 'Query', countries?: Array<{ __typename?: 'Country', id: string, name: string, phoneCode: string } | null> | null };


export const GetCountriesDocument = `
    query getCountries {
  countries {
    id
    name
    phoneCode
  }
}
    `;

const injectedRtkApi = graphqlApiSlice.injectEndpoints({
  overrideExisting: module.hot?.status() === "apply",
  endpoints: (build) => ({
    getCountries: build.query<GetCountriesQuery, GetCountriesQueryVariables | void>({
      query: (variables) => ({ document: GetCountriesDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useGetCountriesQuery, useLazyGetCountriesQuery } = injectedRtkApi;

